name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 5.1.2
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.12.0 <=3.21.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #extended_image: ^4.0.1
  extended_image: 
    git:
         url: https://github.com/sx513240563/extended_image.git
         ref: 54848cd8a54bd6f51865f6c1bc96e7c343a02bbc
  photo_manager: ^1.1.3
  provider: ^5.0.0
  video_player: ^2.1.1
